/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExpenseCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
});
export const TaxRate = IDL.Record({
  'id' : IDL.Nat,
  'cgst' : IDL.Nat,
  'igst' : IDL.Nat,
  'name' : IDL.Text,
  'sgst' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'expenseDate' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'paymentDate' : IDL.Text,
  'category' : IDL.Text,
  'paymentType' : IDL.Text,
  'placeOfSupply' : IDL.Text,
  'amount' : IDL.Nat,
});
export const InvoiceItem = IDL.Record({
  'sellingPrice' : IDL.Nat,
  'productName' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'taxRateId' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'taxRates' : IDL.Vec(TaxRate),
  'invoiceDate' : IDL.Text,
  'signatureUrl' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'placeOfSupply' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'copyType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'pan' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'gstin' : IDL.Text,
  'companyName' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpenseCategory' : IDL.Func([ExpenseCategory], [], []),
  'addTaxRate' : IDL.Func([TaxRate], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExpense' : IDL.Func([Expense], [Expense], []),
  'createInvoice' : IDL.Func([Invoice], [Invoice], []),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'deleteInvoice' : IDL.Func([IDL.Text], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpense' : IDL.Func([IDL.Text], [IDL.Opt(Expense)], ['query']),
  'getExpenseCategories' : IDL.Func([], [IDL.Vec(ExpenseCategory)], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getTaxRates' : IDL.Func([], [IDL.Vec(TaxRate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExpense' : IDL.Func([Expense], [], []),
  'updateInvoice' : IDL.Func([Invoice], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExpenseCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const TaxRate = IDL.Record({
    'id' : IDL.Nat,
    'cgst' : IDL.Nat,
    'igst' : IDL.Nat,
    'name' : IDL.Text,
    'sgst' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'expenseDate' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'paymentDate' : IDL.Text,
    'category' : IDL.Text,
    'paymentType' : IDL.Text,
    'placeOfSupply' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const InvoiceItem = IDL.Record({
    'sellingPrice' : IDL.Nat,
    'productName' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'taxRateId' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'taxRates' : IDL.Vec(TaxRate),
    'invoiceDate' : IDL.Text,
    'signatureUrl' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'placeOfSupply' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'copyType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'pan' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'gstin' : IDL.Text,
    'companyName' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpenseCategory' : IDL.Func([ExpenseCategory], [], []),
    'addTaxRate' : IDL.Func([TaxRate], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExpense' : IDL.Func([Expense], [Expense], []),
    'createInvoice' : IDL.Func([Invoice], [Invoice], []),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'deleteInvoice' : IDL.Func([IDL.Text], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpense' : IDL.Func([IDL.Text], [IDL.Opt(Expense)], ['query']),
    'getExpenseCategories' : IDL.Func(
        [],
        [IDL.Vec(ExpenseCategory)],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getTaxRates' : IDL.Func([], [IDL.Vec(TaxRate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExpense' : IDL.Func([Expense], [], []),
    'updateInvoice' : IDL.Func([Invoice], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };